name: Android
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      actions: write
      attestations: write
      deployments: write
      packages: write
      id-token: write
    strategy:
      matrix:
        include:
          - platform: "windows-latest"
            args: "--target armv7-linux-androideabi,aarch64-linux-android" # 添加多架构支持

    runs-on: ${{ matrix.platform }}

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以便正确生成版本号

      # Rust setup
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      # Rust cache
      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      # Sync node version and setup cache
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      # Install yarn globally
      - name: Install yarn
        run: npm install -g yarn

      # Install frontend dependencies
      - name: Install frontend dependencies
        run: yarn install

      # Windows 环境不需要安装 Ubuntu 特定的依赖
      # 安装 Windows 上需要的依赖
      - name: Install Windows dependencies
        run: |
          choco install openssl

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # 修改 NDK 安装方式 (Windows 路径格式)
      - name: Install Android NDK
        run: |
          # 使用 cmdline-tools 安装 NDK
          & "$env:ANDROID_HOME\cmdline-tools\latest\bin\sdkmanager.bat" --install "ndk;25.1.8937393" --sdk_root="$env:ANDROID_HOME"
          # 设置 NDK_HOME 环境变量
          echo "NDK_HOME=$env:ANDROID_HOME\ndk\25.1.8937393" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "ANDROID_NDK_HOME=$env:ANDROID_HOME\ndk\25.1.8937393" | Out-File -FilePath $env:GITHUB_ENV -Append

      # 修改版本号生成逻辑
      - name: Get date and run number
        id: version # 添加id属性
        run: |
          echo "bundle_version=0.0.${{ github.run_number }}" >> $env:GITHUB_OUTPUT

      - name: Android init
        run: |
          # 显示 NDK 路径
          echo "NDK_HOME: $env:NDK_HOME"
          echo "ANDROID_NDK_HOME: $env:ANDROID_NDK_HOME"
          # 初始化 Android 环境
          yarn run tauri android init

      - name: Android build
        run: |
          # 设置 OpenSSL 环境变量 (Windows 路径)
          $env:OPENSSL_DIR = "C:\Program Files\OpenSSL-Win64"
          $env:OPENSSL_LIB_DIR = "C:\Program Files\OpenSSL-Win64\lib"
          # 构建 Android 应用
          yarn run tauri android build

      # 添加发布到GitHub Release的步骤
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src-tauri/target/android/**/*.apk
            src-tauri/target/android/**/*.aab
          name: Release ${{ github.ref_name }}
          body: |
            Android 应用版本 ${{ steps.version.outputs.bundle_version }}

            自动构建发布
